# develop에 push가되는 상황은
# 배포라고 간주

env:
  DB_PASSWORD: root

#action 이름
name: dev-deploy

#action trigger develop, prod를 제외한 나머지 브랜치에 대해서 푸시되면 동작하도록 한다.
on:
  push:
    #대상 브랜치
    branches: [ develop ]

#실행단위 - 메소드같은 애
jobs:
  #job이름
  dev-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      # ubuntu에 기본으로 깔려있는 mysql 시작
      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE hwamoktest;' -uroot -proot

      # jdk 17 세팅
      - name: Set up JDK 17
        uses: actions/setup-java@main
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      # gradle test 실행
      - name: Integration Test
        uses: gradle/gradle-build-action@main
        with:
          gradle-version: wrapper
          arguments: test

      # Elastic Beanstalk으로 배포를 할 예정
      # EB는 PaaS => Platform as a Service => 관리를 안해도 된다.
      # .zip 이안에는 .ebextentions(optional) Procfile .platform 우리의 jar파일

      #.ebextentions(optional) -> eb의 초기 설정 값
      # Server Timezone -> 전세계공통시간 UTC(default) -> 한국시간 KST(UTC+9) 00자정 -> 15시
      # 00-{이름}.config --> 01-{이름}.config

      # procfiles/Procfile -> 실제로 저희 jar파일 실행하는 명령어가 들어가는 곳

      #.platform/nginx/conf.d -> nginx서버 설정
      # java -jar {name}.jar
      # SaaS => Service as a Service